py_django_quotes/website/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name='home'),
    path("page/<int:page>/", views.main, name='home_paginate'),

    path("author/<int:_id>/", views.author, name='author'),

    path("form_author/", views.form_author, name='form_author'),
    path("form_tag/", views.form_tag, name='form_tag'),
    path("form_quote/", views.form_quote, name='form_quote')
]

py_django_quotes/website/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm


app_name = "users"

urlpatterns = [
     path("signup/", RegisterView.as_view(), name="signup"),
     path("signin/", LoginView.as_view(
               template_name = "users/signin.html",
               authentication_form = LoginForm,
               redirect_authenticated_user = True),
          name="signin"),

     path('logout/', LogoutView.as_view(
               template_name='users/logout.html'),
          name='logout'),
            
     path('reset-password/',
          ResetPasswordView.as_view(
               template_name='users/password_reset.html'),
          name='password_reset'),
    
     path('reset-password/done/', PasswordResetDoneView.as_view(
               template_name='users/password_reset_done.html'),
          name='password_reset_done'),
    
     path('reset-password/confirm/<uidb64>/<token>/',
          PasswordResetConfirmView.as_view(
               template_name='users/password_reset_confirm.html',
               success_url='/users/reset-password/complete/'),
          name='password_reset_confirm'),
    
     path('reset-password/complete/',
          PasswordResetCompleteView.as_view(
              template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),
]

py_django_quotes/website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('quotes.urls')),
    path("users/", include('users.urls')),
]

py_django_quotes/website/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, ModelChoiceField, Select, SelectMultiple

from .models import Author, Tag, Quote


class AuthorForm(ModelForm):
    fullname = CharField(
        max_length=50,
        min_length=3,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter his fullname",
            'id': "fullname"}))
    born_date = CharField(
        max_length=50,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter his bitrhday",
            "id": "born_date"}))
    born_location = CharField(
        max_length=150,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter his where was born",
            "id": "born_location"}))
    description = CharField(
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter something about him",
            "id": "description"}))
    picture = CharField(
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter data:image/jpeg;base64...",
            "id": "picture"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description', 'picture']


class TagForm(ModelForm):
    name = CharField(
        max_length=50,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "New name tag",
            "id": "name"}))

    class Meta:
        model = Tag
        fields = ["name"]


class QuoteForm(ModelForm):
    quote = CharField(
        min_length=5,
        required=True,
        widget=TextInput({
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "New name quote",
            "id": "quote"}))
    tags = ModelMultipleChoiceField(
        queryset=Tag.objects.all().order_by("name"),
        required=True,
        widget=SelectMultiple({
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Chose tags",
            "id": "tags"}))
    author = ModelChoiceField(
        queryset=Author.objects.all().order_by("fullname"),
        widget=Select({
            'class': "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Chose author",
            'id': "author"}))

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

py_django_quotes/website/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from .models import Quote
from .forms import AuthorForm, TagForm, QuoteForm
from .models import Author, Tag


def main(request, page = 1):
    quotes = Quote.objects.all()
    per_page = 12
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/home.html', context={'quotes': quotes_on_page})


@login_required
def form_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:form_tag")
        else:
            return render(request, "quotes/home.html", context={'form': AuthorForm()})
    return render(request, "quotes/form_author.html", context={'form': AuthorForm()})


@login_required
def form_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:form_quote")
        else:
            return render(request, "quotes/home.html", context={'form': TagForm()})
    return render(request, "quotes/form_tag.html", context={'form': TagForm()})


@login_required
def form_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/home.html", context={'form': QuoteForm()})
    return render(request, "quotes/form_quote.html", context={'form': QuoteForm()})


def author(request, _id):
    author = Author.objects.get(pk=_id)
    return render(request, 'quotes/author.html', context={'author': author})

py_django_quotes/website/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'quotes/author.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-ed6c" style="margin-bottom: 20px;">
  <div class="u-clearfix u-sheet u-sheet-1">
    <img class="u-image u-image-round u-radius-10 u-image-1" src="{{ author.picture }}" alt="quote.author.id" data-image-width="500" data-image-height="667">
    <h2 class="u-align-left u-custom-font u-font-roboto-condensed u-text u-text-1">{{ author.fullname }}</h2>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <h5 class="u-align-left u-text u-text-2" style="margin: 50px -40px 0 0px; float: right;">{{ author.description }}</h5>
    <h4 class="u-align-left u-custom-font u-text u-text-font u-text-3" style="padding-left: 40px; padding-top: 350px; padding-right: 40px;">{{ author.born_date }}, {{ author.born_location }}</h4>
  </div>
</section>
{% endblock%}

py_django_quotes/website/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html style="font-size: 16px;" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Quality Construction">
    <meta name="description" content="Here you can see quotes from famous people and add your own if necessary, but first you will need to sign up or log in to your account">

    <!-- title -->
    <title>iPlugin site</title>

    {% load static %}
    <!-- css -->
    <link rel="stylesheet" href="{% static 'quotes/home.css' %}">
    <link rel="stylesheet" href="{% static 'quotes/nicepage.css' %}">
    {% block style %} {% endblock %}
    
    <!-- javascript -->
    <script class="u-script" type="text/javascript" src="{% static 'quotes/jquery.js' %}"></script>
    <script class="u-script" type="text/javascript" src="{% static 'quotes/nicepage.js' %}"></script>

    <!-- google_fonts -->
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i">

    <!-- icon -->
    <link rel="icon" href="{% static 'quotes/images/icon.jpg' %}">
</head>
<body data-home-page="Home.html" data-home-page-title="Home" class="u-body u-overlap u-xl-mode" data-lang="en">
  <header class="u-clearfix u-header" id="sec-64ef" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
    <div class="u-clearfix u-sheet u-sheet-1">
      <a href="https://github.com/iPlugin/goit_hw_pyweb_10" class="u-image u-logo u-image-1" data-image-width="286" data-image-height="95" title="Home">
        <img src="{% static 'quotes/images/logo.jpg' %}" class="u-logo-image u-logo-image-1">
      </a>
      <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
        <div class="u-custom-menu u-nav-container">
          <ul class="u-nav u-unstyled u-nav-1">
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'quotes:home' %}" style="padding: 10px 20px;">&#127969; Home</a></li>
            {% if user.is_authenticated %}
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'quotes:form_author' %}" style="padding: 10px 20px;">&#129333; Upload Author</a></li>
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'quotes:form_quote' %}" style="padding: 10px 20px;">&#128240; Upload Quote</a></li>
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'quotes:form_tag' %}" style="padding: 10px 20px;">&#128206; Upload Tag</a></li>
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'users:logout' %}" style="padding: 10px 20px;">&#128405; Logout</a></li>
            {% else %}
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'users:signin' %}" style="padding: 10px 20px;">&#128400; Sign in</a></li>
            <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'users:signup' %}" style="padding: 10px 20px;">&#128406; Sign up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </header>
  <!-- Attention -->
  {% block content %} {% endblock %}
  <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-43c0">
    <div class="u-clearfix u-sheet u-sheet-1">
      <p class="u-align-center u-text u-text-1">
        <a class="u-border-1 u-border-active-palette-2-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-btn u-button-link u-button-style u-none u-text-body-alt-color u-btn-1" >Copyright © 2023 GoIT. Created by iPlugin.</a>
      </p>
    </div>
  </footer>
</body>
</html>

py_django_quotes/website/quotes/templates/quotes/form_author.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'quotes/upload.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-a612">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Upload Author</h2>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <div class="u-align-center u-form u-form-1">

      {% if messages %}
        <ul class="messages">
      {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
        </ul>
      {% endif %}
      <!-- Form method='POST' -->
      <form action="{% url 'quotes:form_author' %}" method='POST' class="u-form-spacing-10 u-clearfix u-inner-form">  <!-- u-form-vertical -->
        {% csrf_token %}
        <div class="u-form-group u-form-name">
          <label for="fullname" class="u-label">Author name</label>
          {{ form.fullname }}
        </div>
        <div class="u-form-group form-mar_top" style="margin-top: 5px;">
          <label for="born_date" class="u-label">Born</label>
          {{ form.born_date }}
        </div>
        <div class="u-form-group u-form-group-3 form-mar_top" style="margin-top: 5px;">
          <label for="born_location" class="u-label">Place</label>
          {{ form.born_location }}
        </div>
        <div class="u-form-group u-form-group-3 form-mar_top" style="margin-top: 5px;">
          <label for="picture" class="u-label">Photo</label>
          {{ form.picture }}
        </div>
        <div class="u-form-group u-form-textarea u-form-group-4 form-mar_top" style="margin-top: 5px;">
          <label for="description" class="u-label">About Author</label>
          {{ form.description }}
        </div>

        <div class="u-align-right u-form-group">
          <a href="{% url 'quotes:form_tag' %}" style="margin-top: 20px; float: right; margin-left: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">NEXT</a>
        </div>

        <div class="u-align-right u-form-group u-form-submit form-mar_top">
          <a href="#" style="margin-top: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-btn-round u-btn-submit u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">UPLOAD</a>
          <input type="submit" value="submit" class="u-form-control-hidden">
        </div>
      </form>

    </div>
  </div>
</section>
{% endblock%}

py_django_quotes/website/quotes/templates/quotes/form_quote.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'quotes/upload.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-a612">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Upload Quote</h2>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <div class="u-align-center u-form u-form-1">

      <!-- Form method='POST' -->
      <form action="{% url 'quotes:form_quote' %}" class="u-clearfix u-form-spacing-10 u-inner-form" method='POST'> <!-- u-form-vertical -->
        {% csrf_token %}
        <div class="u-form-group u-form-name">
          <label for="name-c87e" class="u-label">Author name</label>
          {{ form.author }}
        </div>

        <div class="u-form-group u-form-textarea u-form-group-4" style="margin-top: 5px;">
          <label for="textarea-4c63" class="u-label">Quote</label>
          {{ form.quote }}
        </div>

        <div class="u-form-group u-form-textarea u-form-group-4" style="margin-top: 5px;">
          <label for="textarea-4c63" class="u-label">Tags</label>
          {{ form.tags }}
        </div>

        <div class="u-align-right u-form-group">
          <a href="{% url 'quotes:home' %}" style="margin-top: 20px; float: right; margin-left: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">HOME</a>
        </div>

        <div class="u-align-right u-form-group u-form-submit">
          <a href="#" style="margin-top: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-btn-round u-btn-submit u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">UPLOAD</a>
          <input type="submit" value="submit" class="u-form-control-hidden">
        </div>
      </form>

    </div>
  </div>
</section>
{% endblock%}

py_django_quotes/website/quotes/templates/quotes/form_tag.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'quotes/upload.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-b3a8">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Upload Tag</h2>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <div class="u-form u-form-1">

      <form action="{% url 'quotes:form_tag' %}" method='POST' class="u-clearfix u-form-spacing-10 u-inner-form"> <!-- u-form-vertical -->
        {% csrf_token %}
        <div class="u-form-group u-form-name">
          <label for="name-8a64" class="u-label">Tag</label>
          {{ form.name }}
        </div>

        <div class="u-align-right u-form-group">
          <a href="{% url 'quotes:form_quote' %}" style="margin-top: 20px; float: right; margin-left: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">NEXT</a>
        </div>

        <div class="u-align-right u-form-group u-form-submit">
          <a href="#" style="margin-top: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-btn-round u-btn-submit u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">UPLOAD</a>
          <input type="submit" value="submit" class="u-form-control-hidden">
        </div>
      </form>

    </div>
  </div>
</section>
{% endblock %}

py_django_quotes/website/quotes/templates/quotes/home.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<section class="u-align-center u-clearfix u-height-50vw-sm u-section-1" id="carousel_ba17">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h1 class="u-custom-font u-font-roboto-condensed u-text u-text-1">Collection ​Quotes</h1>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <p class="u-text u-text-2">Here you can see quotes from famous people and add your own if necessary, but first you will need to sign up or log in to your account</p>
    <div class="u-clearfix u-expanded-width u-gutter-30 u-layout-wrap u-layout-wrap-1">
      <div class="u-gutter-0 u-layout">
        <div class="u-layout-row">

          {% for quote in quotes %}
          <div class="u-align-left u-container-style u-layout-cell u-left-cell u-size-20 u-layout-cell-1">
            <div class="u-container-layout" src="">
              <a href="{% url 'quotes:author' quote.author.id %}">
                <img class="u-image u-image-1" src = "{{ quote.author.picture }}" data-image-width="500" data-image-height="667">
              </a>
              <div class="u-container-style u-group u-palette-1-light-2 u-group-1">
                <div class="u-container-layout u-valign-middle u-container-layout-2">
                  <h4 class="u-text u-text-3">{{ quote.author }}</h4>

                  {% if quote.quote|length > 150 %}
                    <p class="u-text u-text-4">{{ quote.quote|slice:150}} ...</p>
                  {% else %}
                    <p class="u-text u-text-4">{{ quote.quote }}</p>
                  {% endif %}
                    
                  <div class="tags" style="display: block;margin: 15px 0px 0px 0px;">
                    <div class="tag">
                      {% for tag in quote.tags.all %}
                        <text style="padding: 2px 5px;
                        border-radius: 5px;
                        color: white;
                        font-size: smaller;
                        background-color: #7CA3E6;
                        margin: 0px 5px 0px 0px;">{{ tag }}</text>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
            
        </div>
      </div>
    </div>
    <div class="navigation">
      <a class="{% if not quotes.has_previous %} disabled {% endif %}"
      href="{% if quotes.has_previous %} {% url 'quotes:home_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"
      style="
      display: inline-block;
      padding: 0 10px;
      margin: 20px 50px 20px 0px;
      line-height: 50px;
      min-width: 50px;
      background-color: var(--page-link-a-bg-color);
      border-radius: 10px;
      font-weight: 500;
      font-size: 18px;">◀ Back</a>
      <a class="{% if not quotes.has_next %} disabled {% endif %}"
      href="{% if quotes.has_next %} {% url 'quotes:home_paginate' quotes.next_page_number %} {% else %} # {% endif %}"
      style="
      display: inline-block;
      padding: 0 10px;
      margin: 20px 0px 20px 50px;
      line-height: 50px;
      min-width: 50px;
      background-color: var(--page-link-a-bg-color);
      border-radius: 10px;
      font-weight: 500;
      font-size: 18px;">Next ▶</a>
    </div>
  </div>
</section>
{% endblock%}