py_django_quotes/website/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name='home'),
    path("page/<int:page>/", views.main, name='home_paginate'),

    path("author/<int:_id>/", views.author, name='author'),

    path("form_author/", views.form_author, name='form_author'),
    path("form_tag/", views.form_tag, name='form_tag'),
    path("form_quote/", views.form_quote, name='form_quote')
]

py_django_quotes/website/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm


app_name = "users"

urlpatterns = [
     path("signup/", RegisterView.as_view(), name="signup"),
     path("signin/", LoginView.as_view(
               template_name = "users/signin.html",
               authentication_form = LoginForm,
               redirect_authenticated_user = True),
          name="signin"),

     path('logout/', LogoutView.as_view(
               template_name='users/logout.html'),
          name='logout'),
            
     path('reset-password/',
          ResetPasswordView.as_view(
               template_name='users/password_reset.html'),
          name='password_reset'),
    
     path('reset-password/done/', PasswordResetDoneView.as_view(
               template_name='users/password_reset_done.html'),
          name='password_reset_done'),
    
     path('reset-password/confirm/<uidb64>/<token>/',
          PasswordResetConfirmView.as_view(
               template_name='users/password_reset_confirm.html',
               success_url='/users/reset-password/complete/'),
          name='password_reset_confirm'),
    
     path('reset-password/complete/',
          PasswordResetCompleteView.as_view(
              template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),
]

py_django_quotes/website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('quotes.urls')),
    path("users/", include('users.urls')),
]

py_django_quotes/website/users/models.py
from django.db import models

# Create your models here.

py_django_quotes/website/users/forms.py
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm


class RegisterForm(UserCreationForm):
    username = CharField(
        min_length=5,
        max_length=100,
        required=True,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your username"}))
    
    first_name = CharField(
        min_length=3,
        max_length=100,
        required=True,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your first name"}))

    last_name = CharField(
        min_length=3,
        max_length=100,
        required=True,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your last name"}))

    email = EmailField(
        min_length=5,
        max_length=100,
        required=True,
        widget=EmailInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your email"}))

    password1 = CharField(
        max_length=20,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your password"}))

    password2 = CharField(
        max_length=20,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Confirm your password"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(
        max_length=100,
        required=True,
        widget=TextInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your username"}))
    password = CharField(
        max_length=20,
        min_length=6,
        required=True,
        widget=PasswordInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your password"}))

    class Meta:
        model = User
        fields = ("username", "password")


class EmailForm(UserCreationForm):
    email = EmailField(
        min_length=5,
        max_length=100,
        required=True,
        widget=EmailInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your email"}))

class EmailForm(PasswordResetForm):
    password1 = CharField(
        max_length=20,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Enter your password"}))

    password2 = CharField(
        max_length=20,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={
            "class": "u-border-2 u-input u-input-rectangle u-radius-10",
            "placeholder": "Confirm your password"}))

py_django_quotes/website/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from typing import Any
from django.views import View

from .forms import RegisterForm, EmailForm

class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs: Any):
        if self.request.user.is_authenticated:
            return redirect(to="quotes:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Welcome - {username} - your account was created")
            return redirect(to="users:signin")
        return render(request, self.template_name, {"form": form})

def logout(request):
    return render(request, 'users/logout.html', context={})

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

py_django_quotes/website/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'users/logout.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-b3a8">
  <div class="u-clearfix u-sheet u-sheet-1" style="margin-top: 170px; height: 100vh;">
    <h1 class="u-text u-text-default u-text-1" style="text-align: center;">See you later</h1>
    <a href="{% url 'quotes:home' %}" class="u-border-2 u-border-black u-btn u-btn-round u-button-style u-hover-black u-none u-radius-10 u-text-hover-white u-btn-1">Home</a>
  </div>
</section>
{% endblock %}

py_django_quotes/website/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'users/nicepage.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-b3a8">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Reset password</h2>
        <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
        <div class="u-form u-form-1">
  
            {% if form.error %}
                <div class="u-form-send-error">{{ form.non_field_errors }}</div>
            {% endif %}

            {% if messages %}
            {% for msg in messages %}
                <div style="text-align: center; color: #1c9600;">{{ msg }}</div>
            {% endfor %}
            {% endif %}

            <form method="post" class="u-clearfix u-form-spacing-10 u-inner-form" style="padding: 10px;">
                {% csrf_token %}

                <div class="u-form-group u-form-name">
                    <label for="{{form.email.id_for_label}}" class="u-label">Email</label>
                    {{ form.email }}
                    {% if form.error %}
                    <div class="u-form-send-error">{{ form.errors.email }}</div>
                    {% endif %}
                </div>

                <div class="u-align-right u-form-group u-form-submit">
                    <a href="#" style="margin-top: 20px;" class="u-active-black u-border-2 u-border-active-palette-5-dark-2 u-border-black u-border-hover-palette-5-light-1 u-btn u-btn-round u-btn-submit u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-radius-10 u-white u-btn-1">SEND</a>
                    <input type="submit" value="submit" class="u-form-control-hidden">
                </div>
            </form>
  

        </div>
    </div>
</section>

{% endblock %}

py_django_quotes/website/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

py_django_quotes/website/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'users/nicepage.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-b3a8">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Enter new password</h2>
        <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
        <div class="u-form u-form-1">
  
            {% if form.error %}
                <div class="u-form-send-error">{{ form.non_field_errors }}</div>
            {% endif %}

            {% if messages %}
            {% for msg in messages %}
                <div style="text-align: center; color: #1c9600;">{{ msg }}</div>
            {% endfor %}
            {% endif %}

            <form method="post" class="u-clearfix u-form-spacing-10 u-inner-form" style="padding: 10px;">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Save password</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

py_django_quotes/website/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'users/logout.css' %}">
{% endblock %}

{% block content %}

<section class="u-clearfix u-section-1" id="sec-b3a8">
    <div class="u-clearfix u-sheet u-sheet-1" style="margin-top: 150px; height: 100vh;">
      <h2 class="u-text u-text-default u-text-1" style="text-align: center;">Request sent</h2>
      <p style="text-align: center; color: #1c9600;"><i>We've emailed you with instructions on how to reset your password</i></p>
      <a href="{% url 'users:signin' %}" class="u-border-2 u-border-black u-btn u-btn-round u-button-style u-hover-black u-none u-radius-10 u-text-hover-white u-btn-1" style="margin: 0 auto;">SIGN IN</a>
    </div>
  </section>

{% endblock %}

py_django_quotes/website/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

py_django_quotes/website/users/templates/users/signin.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'users/signin.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-b3a8">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Welcome</h2>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <div class="u-form u-form-1">

{% if form.error %}
  <div class="u-form-send-error">{{ form.non_field_errors }}</div>
{% endif %}

{% if messages %}
  {% for msg in messages %}
    <div style="text-align: center; color: #1c9600;"><i>{{ msg }}</i></div>
  {% endfor %}
{% endif %}

      <form action="{% url 'users:signin' %}" class="u-clearfix u-form-spacing-10 u-inner-form" method="post" style="padding: 10px;">
        {% csrf_token %}
        <div class="u-form-group u-form-name">
          <label for="{{form.username.id_for_label}}" class="u-label">Username</label>
          {{ form.username }}
          {% if form.error %}
          <div class="u-form-send-error">{{ form.errors.username }}</div>
          {% endif %}
        </div>

        <div class="u-form-group u-form-name" style="margin-top: 5px;">
          <label for="{{form.password.id_for_label}}" class="u-label">Password</label>
          {{ form.password }}
          {% if form.error %}
          <div class="u-form-send-error">{{ form.errors.password }}</div>
          {% endif %}
        </div>

        <div class="small text-center">
          <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
        </div>

        <div class="u-align-right u-form-group u-form-submit">
          <a href="#" style="margin-top: 20px;" class="u-active-black u-border-2 u-border-active-palette-5-dark-2 u-border-black u-border-hover-palette-5-light-1 u-btn u-btn-round u-btn-submit u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-radius-10 u-white u-btn-1">SINGIN</a>
          <input type="submit" value="submit" class="u-form-control-hidden">
        </div>
      </form>
      
    </div>
  </div>
</section>
{% endblock %}

py_django_quotes/website/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'users/signup.css' %}">
{% endblock %}

{% block content %}
<section class="u-clearfix u-section-1" id="sec-b3a8">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-align-center u-custom-font u-font-roboto-condensed u-text u-text-default u-text-1">Register</h2>
    <div class="u-border-3 u-border-palette-1-base u-line u-line-horizontal u-line-1"></div>
    <div class="u-align-center u-form u-form-1">

{% if form.error %}
<div class="u-form-send-error">{{ form.non_field_errors }}</div>
{% endif %}

      <form action="{% url 'users:signup' %}" class="u-clearfix u-form-spacing-10 u-inner-form" method="post" style="padding: 10px;">
        {% csrf_token %}
        <div class="u-form-group u-form-name">
          <label for="{{form.username.id_for_label}}" class="u-label">Username</label>
          {{ form.username }}
          {% if form.error %}
          <div class="u-form-send-error">{{ form.errors.username }}</div>
          {% endif %}
        </div>
        
        <div class="u-form-email u-form-group" style="margin-top: 5px;">
          <label for="{{form.first_name.id_for_label}}" class="u-label">First name</label>
          {{ form.first_name }}
          {% if form.error %}
          <div class="u-form-send-error">{{ form.errors.first_name }}</div>
          {% endif %}
        </div>
        
        <div class="u-form-group u-form-group-3" style="margin-top: 5px;">
          <label for="{{form.last_name.id_for_label}}" class="u-label">Last name</label>
          {{ form.last_name }}
          {% if form.error %}
          <div class="u-form-send-error">{{ form.errors.last_name }}</div>
          {% endif %}
        </div>
        
        <div class="u-form-group u-form-group-4" style="margin-top: 5px;">
          <label for="{{form.email.id_for_label}}" class="u-label">Email</label>
          {{ form.email }}
          {% if form.error %}
          <div class="u-form-send-error">{{ form.errors.email }}</div>
          {% endif %}
        </div>
        
        <div class="u-form-group u-form-group-5" style="margin-top: 5px;">
          <label for="password1" class="u-label">Password</label>
          {{ form.password1 }}
          <div>{{ form.errors.password1 }}</div>
        </div>

        <div class="u-form-group u-form-group-5" style="margin-top: 5px;">
          <label for="password2" class="u-label">Repeat password</label>
          {{ form.password2 }}
          <div>{{ form.errors.password2 }}</div>
        </div>
        
        <div class="u-align-right u-form-group u-form-submit">
          <a href="#" style="margin-top: 20px;" class="u-active-black u-border-2 u-border-black u-btn u-btn-round u-btn-submit u-button-style u-custom-font u-font-roboto-condensed u-hover-palette-5-dark-2 u-none u-radius-10 u-text-black u-text-hover-white u-btn-1">SINGUP</a>
          <input type="submit" value="submit" class="u-form-control-hidden">
        </div>
      </form>
      
    </div>
  </div>
</section>
{% endblock %}